### ISSUE TITLE
teodorkg link

### ISSUE THREAD

**Issue by teodorkg** [NoHomey/git-talks#5]
https://github.com/teodorkg/fmi_start

**Comment by NoHomey** [comment]
Здравей, разгледах commit-ите ти, с всеки commit си променял по един файл, предполагам, че си ги качвал директно през github. Не случайно съм дал за задание да се добавят два файла и да се commit-нат едновременно с цел да се разцъка git, а не github, за разцъквнето на github съм дал да се отворят по едно issue и pull request. Добави два файла с един commit без значение от инструмента, който ще ползваш. Както показах можеш директно и през повечето IDE-тата да го правиш.
